import { pgTable, text, timestamp, integer, uniqueIndex } from "drizzle-orm/pg-core";

const id = () => text("id").primaryKey();
const createdAt = () => timestamp("created_at", { withTimezone: true }).notNull().defaultNow();
export const users = pgTable("users", { id: id(), name: text("name"), email: text("email").unique(), emailVerified: timestamp("email_verified", { withTimezone: true }), image: text("image") });
export const accounts = pgTable("accounts", { userId: text("user_id").notNull(), type: text("type").notNull(), provider: text("provider").notNull(), providerAccountId: text("provider_account_id").notNull(), refresh_token: text("refresh_token"), access_token: text("access_token"), expires_at: integer("expires_at"), token_type: text("token_type"), scope: text("scope"), id_token: text("id_token"), session_state: text("session_state") }, (t) => [uniqueIndex("accounts_provider_account").on(t.provider, t.providerAccountId)]);
export const sessions = pgTable("sessions", { sessionToken: text("session_token").primaryKey(), userId: text("user_id").notNull(), expires: timestamp("expires", { withTimezone: true }).notNull() });
export const verificationTokens = pgTable("verification_tokens", { identifier: text("identifier").notNull(), token: text("token").notNull(), expires: timestamp("expires", { withTimezone: true }).notNull() }, (t) => [uniqueIndex("verification_token").on(t.identifier, t.token)]);
export const journalSides = pgTable("journal_sides", { id: id(), ownerId: text("owner_id").notNull(), color: text("color").notNull(), name: text("name").notNull(), position: integer("position").notNull(), createdAt: createdAt(), archivedAt: timestamp("archived_at", { withTimezone: true }) }, (t) => [uniqueIndex("side_name_per_owner").on(t.ownerId, t.name)]);
export const conversations = pgTable("conversations", { id: id(), ownerId: text("owner_id").notNull(), title: text("title").notNull(), archivedAt: timestamp("archived_at", { withTimezone: true }), createdAt: createdAt(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() });
export const messages = pgTable("messages", { id: id(), conversationId: text("conversation_id").notNull(), authorSideId: text("author_side_id").notNull(), body: text("body").notNull(), kind: text("kind").notNull().default("text"), replyToMessageId: text("reply_to_message_id"), threadRootId: text("thread_root_id"), editedAt: timestamp("edited_at", { withTimezone: true }), deletedAt: timestamp("deleted_at", { withTimezone: true }), createdAt: createdAt() });
export const messageReactions = pgTable("message_reactions", { messageId: text("message_id").notNull(), sideId: text("side_id").notNull(), reaction: text("reaction").notNull(), createdAt: createdAt() }, (t) => [uniqueIndex("reaction_once_per_side").on(t.messageId, t.sideId, t.reaction)]);
export const attachments = pgTable("attachments", { id: id(), messageId: text("message_id").notNull(), storageKey: text("storage_key").notNull(), mimeType: text("mime_type").notNull(), byteSize: integer("byte_size").notNull(), width: integer("width"), height: integer("height"), uploadState: text("upload_state").notNull().default("pending"), createdAt: createdAt() });
export const preferences = pgTable("preferences", { ownerId: text("owner_id").primaryKey(), appearance: text("appearance").notNull().default("system"), installDismissed: timestamp("install_dismissed", { withTimezone: true }) });
