"use client";
import { Archive, ChevronLeft, CirclePlus, Ellipsis, FileUp, Search, Send, Smile, RotateCw, Plus, X } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import { InstallButton } from "./install-button";

type Side = { id: string; name: string; color: string };
type Message = { id: number; side: string; body: string; time: string; reaction?: string; reply?: string };
const sideSeed: Side[] = [{ id: "violet", name: "Violet", color: "#8179c4" }, { id: "moss", name: "Moss", color: "#6fa281" }, { id: "amber", name: "Amber", color: "#cf9951" }];
const initialMessages: Message[] = [{ id: 1, side: "violet", body: "I keep thinking I wasted the whole weekend.", time: "8:42 PM" }, { id: 2, side: "moss", body: "You rested, called Mom, and made the list. That doesn’t sound wasted.", time: "8:43 PM", reaction: "💛 1  ·  🙌" }, { id: 3, side: "violet", body: "Okay. What is one tiny thing I can do before bed?", time: "8:45 PM", reply: "Moss · You rested, called Mom…" }, { id: 4, side: "amber", body: "Put on tea. Then choose one thing for tomorrow. 🌙", time: "8:46 PM" }];
const threads = ["Sunday reset", "Work spiral", "Things I’m proud of"];
export function Journal() {
  const [sides, setSides] = useState(sideSeed); const [active, setActive] = useState(0); const [messages, setMessages] = useState(initialMessages); const [draft, setDraft] = useState(""); const [thread, setThread] = useState("Sunday reset"); const [query, setQuery] = useState(""); const [showSides, setShowSides] = useState(false); const current = sides[active];
  const filtered = useMemo(() => messages.filter((message) => message.body.toLowerCase().includes(query.toLowerCase())), [messages, query]);
  function send(event: FormEvent) { event.preventDefault(); const body = draft.trim(); if (!body) return; setMessages((all) => [...all, { id: Date.now(), side: current.id, body, time: new Intl.DateTimeFormat(undefined, { hour: "numeric", minute: "2-digit" }).format(new Date()) }]); setDraft(""); }
  function cycle() { setActive((index) => (index + 1) % sides.length); }
  function addSide() { const available = ["Rose", "Sky", "Coral", "Indigo", "Teal"]; const name = available.find((candidate) => !sides.some((side) => side.name === candidate)); if (name) setSides((all) => [...all, { id: name.toLowerCase(), name, color: "#668bb7" }]); setShowSides(false); }
  return <main className="shell">
    <header className="appbar"><div className="brand">Self<span>Talk</span></div><div className="account"><InstallButton /><span>Alex’s private journal</span><div className="avatar">A</div></div></header>
    <div className="app-layout"><aside className="library"><button className="new-thread" onClick={() => setThread("Untitled conversation")}> <CirclePlus size={18} /> New conversation</button><label className="search"><Search size={15} /><input aria-label="Search conversations" placeholder="Search conversations" /></label><p className="library-label">Your conversations</p>{threads.map((name) => <button className={`thread ${thread === name ? "selected" : ""}`} key={name} onClick={() => setThread(name)}><b>{name}</b><small>{name === "Sunday reset" ? "Okay. What is one tiny thing I can do…" : "A private place to keep talking."}</small></button>)}<p className="library-label">Archived</p><button className="thread"><b>Apartment hunt</b><small>Closed · 6 messages</small></button><button className="archive"><Archive size={15} /> Manage archived</button></aside>
      <section className="chat"><header className="chat-header"><button className="mobile-back" aria-label="Back to conversations"><ChevronLeft /></button><div className="persona"><b><i style={{ background: current.color }} />{current.name}</b><small>{thread} · current side</small></div><div className="chat-actions"><Search size={18} /><Ellipsis size={20} /></div></header>
        <div className="messages" aria-live="polite">{filtered.map((message) => { const mine = message.side === current.id; const author = sides.find((side) => side.id === message.side); return <article key={message.id} className={`message ${mine ? "right" : "left"}`}><div className="bubble" style={{ background: mine ? current.color : author?.color }}><button className="message-menu" aria-label="Message actions"><Ellipsis size={15} /></button>{message.reply && <div className="reply">↪ {message.reply}</div>}{message.body}</div><small>{author?.name} · {message.time}</small>{message.reaction && <button className="reaction">{message.reaction} <Plus size={12} /></button>}</article>; })}</div>
        <form className="composer" onSubmit={send}><button type="button" className="icon-button" title="Attach private file"><FileUp size={20} /></button><input value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="Write what’s true…" aria-label="Message" /><button type="button" className="icon-button" title="Choose emoji"><Smile size={20} /></button><button type="button" className="cycler" onClick={cycle} title={`Switch to ${sides[(active + 1) % sides.length].name}`} aria-label="Switch to next side"><RotateCw size={18} /></button><button className="send" aria-label="Send message"><Send size={18} /></button></form>
      </section></div>
    <button className="side-manager" onClick={() => setShowSides(true)}>Sides · {sides.map((side) => side.name).join(" / ")}</button>{showSides && <div className="modal-backdrop" onClick={() => setShowSides(false)}><section className="side-modal" onClick={(event) => event.stopPropagation()}><button className="close" onClick={() => setShowSides(false)}><X /></button><h2>Your sides</h2><p>Each color-named side is another perspective in your journal.</p>{sides.map((side, index) => <button key={side.id} className="side-row" onClick={() => { setActive(index); setShowSides(false); }}><i style={{ background: side.color }} />{side.name}<span>{index === active ? "Current" : ""}</span></button>)}<button className="add-side" onClick={addSide}> <Plus size={16} /> Add another side</button></section></div>}</main>;
}
