import { TextStyle, ViewStyle } from 'react-native';
import { Theme } from '@flyerhq/react-native-chat-ui';

export function getStyles(theme: Theme) {
    const fontFamily = 'System'; // Define the font globally

    return {
        baseContainer: {
            flex: 1,
            backgroundColor: theme.colors.background,
        } as ViewStyle,
        container: {
            flex: 1,
            padding: 20,
            backgroundColor: theme.colors.background,
        } as ViewStyle,
        title: {
            fontSize: 28,
            color: theme.colors.primary,
            fontWeight: 'bold',
            textAlign: 'center',
            marginBottom: 20,
            fontFamily,
        } as TextStyle,
        subtitle: {
            fontSize: 16,
            color: theme.colors.inputText,
            textAlign: 'center',
            marginBottom: 20,
            fontFamily,
        } as TextStyle,
        section: {
            marginBottom: 30,
        } as ViewStyle,
        label: {
            fontSize: 18,
            fontWeight: 'bold',
            color: theme.colors.primary,
            marginBottom: 10,
            fontFamily,
        } as TextStyle,
        input: {
            borderWidth: 1,
            borderColor: theme.colors.primary,
            backgroundColor: theme.colors.inputBackground,
            paddingVertical: 10,
            paddingHorizontal: 15,
            borderRadius: 8,
            fontSize: 16,
            color: theme.colors.inputText,
            marginBottom: 15,
            fontFamily,
        } as TextStyle,
        button: {
            backgroundColor: theme.colors.primary,
            paddingVertical: 15,
            paddingHorizontal: 20,
            borderRadius: 8,
            shadowColor: theme.colors.background,
            shadowOpacity: 0.2,
            shadowRadius: 4,
            shadowOffset: { width: 0, height: 2 },
            alignItems: 'center',
            marginBottom: 15,
        } as ViewStyle,
        buttonText: {
            color: theme.colors.inputText,
            fontSize: 16,
            fontWeight: '600',
            fontFamily,
        } as TextStyle,
        header: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            backgroundColor: theme.colors.inputBackground,
            paddingTop: 10,
            paddingBottom: 8,
        } as ViewStyle,
        headerTitle: {
            fontSize: 30,
            fontFamily: 'Trebuchet MS', // Keeping this different font as per original code
            color: theme.colors.inputText,
            marginTop: -3.1,
            paddingLeft: 10,
        } as TextStyle,
        iconStyle: {
            paddingLeft: 10,
            paddingRight: 10,
        } as ViewStyle,
        menuOptionsContainer: {
            backgroundColor: theme.colors.secondary,
            borderRadius: 20,
            borderColor: theme.colors.background,
            borderWidth: 1.5,
        } as ViewStyle,
        menuOptionText: {
            color: theme.colors.inputText,
            padding: 10,
            fontFamily,
        } as TextStyle,
        padded: {
            padding: 20,
        } as ViewStyle,
        colorPicker: {
            centeredText: {
                fontWeight: 'bold',
                textAlign: 'center',
                color: 'white',
                fontFamily,
            } as TextStyle,
            container: {
                flex: 1,
                justifyContent: 'center',
                alignContent: 'center',
                backgroundColor: 'orange',
            },
            pickerContainer: {
                alignSelf: 'center',
                width: 300,
                backgroundColor: '#fff',
                padding: 20,
                borderRadius: 20,
                shadowColor: '#000',
                shadowOffset: {
                    width: 0,
                    height: 5,
                },
                shadowOpacity: 0.34,
                shadowRadius: 6.27,
                elevation: 10,
            } as ViewStyle,
            sliderTitle: {
                color: '#000',
                fontWeight: 'bold',
                marginBottom: 5,
                paddingHorizontal: 4,
                fontFamily,
            } as TextStyle,
            sliderStyle: {
                borderRadius: 20,
                marginBottom: 20,
                shadowColor: '#000',
                shadowOffset: {
                    width: 0,
                    height: 2,
                },
                shadowOpacity: 0.25,
                shadowRadius: 3.84,
                elevation: 5,
            },
            previewTxtContainer: {
                paddingTop: 20,
                marginTop: 20,
                borderTopWidth: 1,
                borderColor: '#bebdbe',
            },
            swatchesContainer: {
                paddingTop: 20,
                marginTop: 20,
                borderTopWidth: 1,
                borderColor: '#bebdbe',
                alignItems: 'center',
                flexWrap: 'nowrap',
                gap: 10,
            },
            swatchStyle: {
                borderRadius: 20,
                height: 30,
                width: 30,
                margin: 0,
            },
            openButton: {
                borderRadius: 20,
                paddingHorizontal: 40,
                paddingVertical: 10,
                marginVertical: 5,
                backgroundColor: '#fff',
                shadowColor: '#000',
                shadowOffset: {
                    width: 0,
                    height: 2,
                },
                shadowOpacity: 0.25,
                shadowRadius: 3.84,
                elevation: 5,
            },
            closeButton: {
                position: 'absolute',
                bottom: 10,
                borderRadius: 20,
                paddingHorizontal: 40,
                paddingVertical: 10,
                alignSelf: 'center',
                backgroundColor: '#fff',
                shadowColor: '#000',
                shadowOffset: {
                    width: 0,
                    height: 2,
                },
                shadowOpacity: 0.25,
                shadowRadius: 3.84,
                elevation: 5,
            } as ViewStyle,
        },
    };
}