import postgres from "postgres";

const PALETTE = [["Violet", "#8179c4"], ["Indigo", "#668bb7"], ["Blue", "#5b9bd5"], ["Teal", "#4fa89c"], ["Moss", "#6fa281"], ["Green", "#74b66c"], ["Lime", "#a8bd58"], ["Amber", "#cf9951"], ["Orange", "#df7d4d"], ["Coral", "#dd6d69"], ["Rose", "#d36e83"], ["Pink", "#c878ac"], ["Plum", "#9d6fb5"], ["Slate", "#77849b"], ["Stone", "#9b927d"], ["Sand", "#c5ad82"]];
const sql = postgres(process.env.DATABASE_URL);
await sql.unsafe(`CREATE TABLE IF NOT EXISTS users (id text PRIMARY KEY, name text, email text UNIQUE, email_verified timestamptz, image text); CREATE TABLE IF NOT EXISTS accounts (user_id text NOT NULL, type text NOT NULL, provider text NOT NULL, provider_account_id text NOT NULL, refresh_token text, access_token text, expires_at integer, token_type text, scope text, id_token text, session_state text, UNIQUE(provider, provider_account_id)); CREATE TABLE IF NOT EXISTS sessions (session_token text PRIMARY KEY, user_id text NOT NULL, expires timestamptz NOT NULL); CREATE TABLE IF NOT EXISTS verification_tokens (identifier text NOT NULL, token text NOT NULL, expires timestamptz NOT NULL, UNIQUE(identifier, token)); CREATE TABLE IF NOT EXISTS journal_sides (id text PRIMARY KEY, owner_id text NOT NULL, color text NOT NULL, name text NOT NULL, position integer NOT NULL, is_enabled integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), archived_at timestamptz, UNIQUE(owner_id, name)); ALTER TABLE journal_sides ADD COLUMN IF NOT EXISTS is_enabled integer NOT NULL DEFAULT 1; CREATE TABLE IF NOT EXISTS conversations (id text PRIMARY KEY, owner_id text NOT NULL, title text NOT NULL, position integer NOT NULL DEFAULT 0, archived_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()); ALTER TABLE conversations ADD COLUMN IF NOT EXISTS position integer NOT NULL DEFAULT 0; CREATE TABLE IF NOT EXISTS messages (id text PRIMARY KEY, conversation_id text NOT NULL, author_side_id text NOT NULL, body text NOT NULL, kind text NOT NULL DEFAULT 'text', reply_to_message_id text, thread_root_id text, edited_at timestamptz, deleted_at timestamptz, created_at timestamptz NOT NULL DEFAULT now()); CREATE TABLE IF NOT EXISTS message_reactions (message_id text NOT NULL, side_id text NOT NULL, reaction text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(message_id, side_id, reaction)); CREATE TABLE IF NOT EXISTS preferences (owner_id text PRIMARY KEY, appearance text NOT NULL DEFAULT 'system', install_dismissed timestamptz);`);
const distance = (a, b) => { const rgb = (value) => /^#[0-9a-f]{6}$/i.test(value) ? [1, 3, 5].map((start) => Number.parseInt(value.slice(start, start + 2), 16)) : [128, 128, 128]; const [ar, ag, ab] = rgb(a); const [br, bg, bb] = rgb(b); return (ar - br) ** 2 + (ag - bg) ** 2 + (ab - bb) ** 2; };
for (const { owner_id: ownerId } of await sql`SELECT DISTINCT owner_id FROM journal_sides`) await sql.begin(async (tx) => {
  const old = await tx`SELECT id, color, position, archived_at FROM journal_sides WHERE owner_id = ${ownerId} ORDER BY position, created_at`;
  if (old.length === 16 && old.every((side, index) => side.color === PALETTE[index][1])) return;
  const available = new Set(PALETTE.map((_, index) => index)); const mapped = new Map();
  for (const side of old) { const choices = available.size ? [...available] : PALETTE.map((_, index) => index); const target = choices.reduce((best, index) => distance(side.color, PALETTE[index][1]) < distance(side.color, PALETTE[best][1]) ? index : best, choices[0]); available.delete(target); mapped.set(side.id, target); }
  await tx`UPDATE journal_sides SET name = CONCAT('__legacy_', id) WHERE owner_id = ${ownerId}`;
  const ids = PALETTE.map(() => crypto.randomUUID()); const enabled = PALETTE.map(() => 1);
  for (const side of old) if (side.archived_at) enabled[mapped.get(side.id)] = 0;
  for (const [index, [name, color]] of PALETTE.entries()) await tx`INSERT INTO journal_sides (id, owner_id, color, name, position, is_enabled) VALUES (${ids[index]}, ${ownerId}, ${color}, ${name}, ${index}, ${enabled[index]})`;
  for (const side of old) { const targetId = ids[mapped.get(side.id)]; await tx`INSERT INTO message_reactions (message_id, side_id, reaction, created_at) SELECT message_id, ${targetId}, reaction, created_at FROM message_reactions WHERE side_id = ${side.id} ON CONFLICT DO NOTHING`; await tx`UPDATE messages SET author_side_id = ${targetId} WHERE author_side_id = ${side.id}`; await tx`DELETE FROM message_reactions WHERE side_id = ${side.id}`; }
  await tx`DELETE FROM journal_sides WHERE owner_id = ${ownerId} AND name LIKE '__legacy_%'`;
});
await sql.end();
